// 测字算卦数据

// 笔画数据库（常用字，无重复）
export const charStrokes: Record<string, number> = {
  // 一画
  '一': 1, '乙': 1,
  // 二画
  '二': 2, '十': 2, '丁': 2, '七': 2, '入': 2, '了': 2, '力': 2, '刀': 2,
  // 三画
  '三': 3, '口': 3, '大': 3, '女': 3, '子': 3, '小': 3, '山': 3, '工': 3, '己': 3, '士': 3, '干': 3, '寸': 3, '弓': 3, '才': 3, '之': 3, '丸': 3, '久': 3, '义': 3, '也': 3,
  // 四画
  '四': 5, '五': 4, '六': 4, '王': 4, '木': 4, '水': 4, '火': 4, '天': 4, '无': 4, '元': 4, '云': 4, '互': 4, '井': 4, '开': 4, '夫': 4, '太': 4, '不': 4, '丰': 4, '支': 4, '日': 4, '曰': 4, '月': 4, '气': 4, '介': 4, '父': 4, '分': 4, '公': 4, '手': 4, '毛': 4, '牛': 4, '犬': 4, '中': 4, '内': 4, '长': 4, '升': 4, '车': 4, '仆': 4, '为': 4, '凤': 4,
  // 五画
  '本': 5, '术': 5, '东': 5, '北': 5, '由': 5, '甲': 5, '申': 5, '电': 5, '田': 5, '史': 5, '只': 5, '兄': 5, '出': 5, '生': 5, '失': 5, '乍': 5, '乎': 5, '丛': 5, '乐': 5, '丝': 5, '主': 5, '仕': 5, '付': 5, '仙': 5, '代': 5, '令': 5, '以': 5, '仪': 5, '们': 5, '件': 5, '任': 5, '伊': 5, '伍': 5, '伏': 5, '伐': 5, '休': 5, '众': 5, '优': 5, '伙': 5, '外': 5, '左': 5, '右': 5, '发': 5, '去': 5, '功': 5, '业': 5, '宁': 5, '旧': 5, '龙': 5,
  // 六画
  '年': 6, '地': 6, '在': 6, '有': 6, '那': 6, '好': 6, '多': 6, '里': 7, '成': 6, '名': 6, '华': 6, '合': 6, '兴': 6, '达': 6, '会': 6, '伟': 6, '传': 6, '吉': 6, '安': 6, '收': 6, '买': 6, '迁': 6, '行': 6, '动': 6, '讼': 6, '臣': 6, '她': 6, '作': 7, '寿': 7, '运': 7,
  // 七画
  '来': 7, '我': 7, '你': 7, '这': 7, '低': 7, '利': 7, '求': 7, '进': 7, '走': 7, '医': 7, '余': 7, '否': 7, '败': 7, '身': 7, '投': 7, '君': 7,
  // 八画
  '金': 8, '官': 8, '旺': 8, '昌': 8, '妻': 8, '学': 8, '房': 8, '非': 8, '性': 8, '命': 8, '和': 8, '朋': 8, '事': 8, '明': 8, '考': 6, '试': 8,
  // 常用测字吉字
  '福': 14, '禄': 12, '喜': 12, '财': 7, '爱': 10, '缘': 12, '康': 11, '顺': 9, '通': 10, '贵': 9, '富': 12, '荣': 9, '祥': 10, '瑞': 13, '美': 9, '满': 13, '圆': 10, '聚': 14, '强': 12, '盛': 11, '获': 10, '胜': 9, '赢': 17, '盈': 9,
  // 常用测字问事
  '问': 11, '婚': 11, '姻': 9, '情': 11, '恋': 10, '职': 11, '商': 11, '贾': 10, '卖': 8, '资': 10, '病': 10, '药': 9, '是': 9, '得': 11, '退': 9, '往': 8, '留': 10, '止': 4, '静': 14,
  // 常用测字问人（已定义的不再重复：人、己、心、友）
  '母': 5, '客': 9, '敌': 10, '亲': 9, '故': 9, '新': 13, '弟': 7,
  // 其他常用字（已定义的不再重复）
  '能': 10, '说': 9, '要': 9, '看': 9, '想': 13, '做': 11, '高': 10, '短': 12, '宽': 10, '窄': 10, '它': 5, '就': 12,
};

// 字形拆解数据（常用测字）
export interface CharDecomposition {
  char: string;
  strokes: number;
  parts: string[];           // 拆解后的部件
  meanings: string[];        // 各部件含义
  overall: string;           // 整体解读
  fiveElement: string;       // 五行属性
  yinYang: string;           // 阴阳属性
}

export const charDecompositions: Record<string, CharDecomposition> = {
  '福': {
    char: '福',
    strokes: 14,
    parts: ['示', '一', '口', '田'],
    meanings: ['示为神示，有神灵保佑之意', '一口田，衣食无忧', '田产丰足，家业兴旺'],
    overall: '福字从示，示神意也。一口田，寓意衣食无忧，田产丰足。此字大吉，主福禄双全，家宅安宁。',
    fiveElement: '土',
    yinYang: '阳',
  },
  '禄': {
    char: '禄',
    strokes: 12,
    parts: ['示', '录'],
    meanings: ['示为神示，天赐之意', '录为记录，登科录取'],
    overall: '禄从示从录，天赐官禄，登科及第。主仕途顺遂，功名有望，财官双美。',
    fiveElement: '金',
    yinYang: '阳',
  },
  '寿': {
    char: '寿',
    strokes: 7,
    parts: ['丰', '寸'],
    meanings: ['丰为丰盛圆满', '寸为度量，寸阴寸金'],
    overall: '寿字丰寸相合，丰衣足食，寸阴是竞。主健康长寿，晚年享福，子孙满堂。',
    fiveElement: '水',
    yinYang: '阴',
  },
  '喜': {
    char: '喜',
    strokes: 12,
    parts: ['士', '口', '丷', '一', '口'],
    meanings: ['士为读书人', '口为言语欢笑', '双口成喜，好事成双'],
    overall: '喜字士口相承，双口成喜。主喜事临门，婚姻美满，人丁兴旺。',
    fiveElement: '火',
    yinYang: '阳',
  },
  '财': {
    char: '财',
    strokes: 7,
    parts: ['贝', '才'],
    meanings: ['贝为古钱币，财富之象', '才为才能才华'],
    overall: '财从贝从才，有才方能聚财。主财运亨通，才华变现，富贵可期。',
    fiveElement: '金',
    yinYang: '阳',
  },
  '爱': {
    char: '爱',
    strokes: 10,
    parts: ['爫', '冖', '友'],
    meanings: ['爫为手，呵护之意', '冖为屋檐，庇护', '友为朋友，情谊'],
    overall: '爱字手护友于心，情真意切。主姻缘和合，情投意合，家庭和睦。',
    fiveElement: '土',
    yinYang: '阴',
  },
  '缘': {
    char: '缘',
    strokes: 12,
    parts: ['纟', '彖'],
    meanings: ['纟为丝线，牵连不断', '彖为判断，决断'],
    overall: '缘从丝从彖，千里姻缘一线牵。主缘分天定，遇贵人相助，良缘可期。',
    fiveElement: '木',
    yinYang: '阴',
  },
  '命': {
    char: '命',
    strokes: 8,
    parts: ['人', '一', '口', '卩'],
    meanings: ['人一口，人之命脉', '卩为节，有节制'],
    overall: '命字人一口节，命中注定有定数。主命运有轨迹，但人为可改，积德行善可转命。',
    fiveElement: '水',
    yinYang: '阴',
  },
  '运': {
    char: '运',
    strokes: 7,
    parts: ['辶', '云'],
    meanings: ['辶为行走，行动', '云为云气，变化'],
    overall: '运从走从云，运气如云行不定。主运势流转，时来运转，顺势而为方得吉。',
    fiveElement: '土',
    yinYang: '阳',
  },
  '吉': {
    char: '吉',
    strokes: 6,
    parts: ['士', '口'],
    meanings: ['士为有识之士', '口为言语，吉祥之言'],
    overall: '吉字士口相合，君子言善。主万事顺遂，逢凶化吉，诸事如意。',
    fiveElement: '木',
    yinYang: '阳',
  },
  '安': {
    char: '安',
    strokes: 6,
    parts: ['宀', '女'],
    meanings: ['宀为屋檐，家宅', '女为女子，家庭'],
    overall: '安字女在屋下，家中有女为安。主家庭和睦，平安顺遂，居有定所。',
    fiveElement: '土',
    yinYang: '阴',
  },
  '康': {
    char: '康',
    strokes: 11,
    parts: ['广', '隶'],
    meanings: ['广为宽广', '隶为附属'],
    overall: '康字广隶相承，心宽体健。主健康长寿，身心安康，生活富足。',
    fiveElement: '木',
    yinYang: '阳',
  },
  '成': {
    char: '成',
    strokes: 6,
    parts: ['戊', '丁'],
    meanings: ['戊为兵器，进取', '丁为火，旺盛'],
    overall: '成字戊丁相合，功成名就。主事业有成，诸事顺利，马到成功。',
    fiveElement: '金',
    yinYang: '阳',
  },
  '功': {
    char: '功',
    strokes: 5,
    parts: ['工', '力'],
    meanings: ['工为工作', '力为力量，努力'],
    overall: '功字工力相合，辛勤出功绩。主功成名就，付出有回报，勤奋可成。',
    fiveElement: '木',
    yinYang: '阳',
  },
  '名': {
    char: '名',
    strokes: 6,
    parts: ['夕', '口'],
    meanings: ['夕为夕阳，晚', '口为名声，传扬'],
    overall: '名字夕口相合，名声远扬。主名声渐起，有名望，但需积德方可长久。',
    fiveElement: '水',
    yinYang: '阴',
  },
  '利': {
    char: '利',
    strokes: 7,
    parts: ['禾', '刂'],
    meanings: ['禾为庄稼，收获', '刂为刀，收割'],
    overall: '利字禾刀相合，收获之时。主利益可图，财利双收，但需正道取利。',
    fiveElement: '金',
    yinYang: '阳',
  },
  '龙': {
    char: '龙',
    strokes: 5,
    parts: ['尤', '匕'],
    meanings: ['龙为神兽', '变化飞腾'],
    overall: '龙字为神龙之象，飞龙在天。主事业腾飞，贵不可言，但需把握时机。',
    fiveElement: '土',
    yinYang: '阳',
  },
  '凤': {
    char: '凤',
    strokes: 4,
    parts: ['几', '又'],
    meanings: ['凤为神鸟', '涅槃重生'],
    overall: '凤字为凤凰之象，百鸟之王。主高贵典雅，婚姻美满，有贵人相助。',
    fiveElement: '火',
    yinYang: '阴',
  },
  '婚': {
    char: '婚',
    strokes: 11,
    parts: ['女', '昏'],
    meanings: ['女为女子', '昏为黄昏，古人黄昏迎亲'],
    overall: '婚字女昏相合，黄昏迎亲。主姻缘将至，婚期可期，但需择良辰吉日。',
    fiveElement: '水',
    yinYang: '阴',
  },
  '子': {
    char: '子',
    strokes: 3,
    parts: ['了一'],
    meanings: ['子为子女', '延续香火'],
    overall: '子字简单有力，生生不息。主添丁之喜，子嗣有继，后代昌盛。',
    fiveElement: '水',
    yinYang: '阳',
  },
  '学': {
    char: '学',
    strokes: 8,
    parts: ['⺍', '冖', '子'],
    meanings: ['学习知识', '学子'],
    overall: '学字上有文思，下有学子。主学业有成，考试顺利，金榜题名。',
    fiveElement: '水',
    yinYang: '阴',
  },
  '升': {
    char: '升',
    strokes: 4,
    parts: ['丿', '廾'],
    meanings: ['上升之意', '步步高升'],
    overall: '升字上升之象，如日方升。主事业上升，职位晋升，前途光明。',
    fiveElement: '金',
    yinYang: '阳',
  },
  '问': {
    char: '问',
    strokes: 11,
    parts: ['门', '口'],
    meanings: ['门为门户', '口为言语询问'],
    overall: '问字门口相合，叩门求问。主所问之事有回应，贵人指点，答案将至。',
    fiveElement: '金',
    yinYang: '阴',
  },
  '事': {
    char: '事',
    strokes: 8,
    parts: ['一', '口', '彐', '亅'],
    meanings: ['事务繁多', '需用心经营'],
    overall: '事字繁复，主事务繁多。需专心致志，循序渐进，方能成事。',
    fiveElement: '金',
    yinYang: '阴',
  },
  '求': {
    char: '求',
    strokes: 7,
    parts: ['一', '氺', '丶'],
    meanings: ['求索', '水滴石穿'],
    overall: '求字水滴下注，持之以恒。主所求之事需耐心，持之以恒方能有成。',
    fiveElement: '水',
    yinYang: '阴',
  },
  '心': {
    char: '心',
    strokes: 4,
    parts: ['⺄', '丶', '丶', '丶'],
    meanings: ['心为心脏', '心神，心念'],
    overall: '心字三点环绕，心神所系。主心事重重，需放下执念，心诚则灵。',
    fiveElement: '火',
    yinYang: '阴',
  },
  '人': {
    char: '人',
    strokes: 2,
    parts: ['丿', '乀'],
    meanings: ['人为万物之灵', '立于天地之间'],
    overall: '人字一撇一捺，立于天地。主有人相助，贵人出现，人际和谐。',
    fiveElement: '金',
    yinYang: '阳',
  },
  '水': {
    char: '水',
    strokes: 4,
    parts: ['亅', '㇇', '㇏'],
    meanings: ['水为生命之源', '流动变化'],
    overall: '水字流动不息，润泽万物。主财运流动，变化在即，顺水推舟。',
    fiveElement: '水',
    yinYang: '阴',
  },
  '山': {
    char: '山',
    strokes: 3,
    parts: ['│', '㇑', '㇑'],
    meanings: ['山为稳重', '高远'],
    overall: '山字三峰耸立，稳重高远。主根基稳固，稳步上升，贵人如山。',
    fiveElement: '土',
    yinYang: '阳',
  },
  '明': {
    char: '明',
    strokes: 8,
    parts: ['日', '月'],
    meanings: ['日为太阳', '月为月亮，日月同辉'],
    overall: '明字日月相合，光明磊落。主前途光明，是非分明，贵人照耀。',
    fiveElement: '火',
    yinYang: '阳',
  },
  '好': {
    char: '好',
    strokes: 6,
    parts: ['女', '子'],
    meanings: ['女为女子', '子为子女，女子相伴'],
    overall: '好字女子相合，儿女双全。主婚姻美满，家庭幸福，诸事顺遂。',
    fiveElement: '水',
    yinYang: '阴',
  },
  '天': {
    char: '天',
    strokes: 4,
    parts: ['一', '大'],
    meanings: ['一为大', '天为至高'],
    overall: '天字一大，至高无上。主天赐良机，顺天而行，必有大成。',
    fiveElement: '金',
    yinYang: '阳',
  },
  '地': {
    char: '地',
    strokes: 6,
    parts: ['土', '也'],
    meanings: ['土为土地', '也为语气词'],
    overall: '地字土也相合，厚德载物。主根基稳固，脚踏实地，稳步发展。',
    fiveElement: '土',
    yinYang: '阴',
  },
  '日': {
    char: '日',
    strokes: 4,
    parts: ['口', '一'],
    meanings: ['太阳', '光明'],
    overall: '日字方正，光芒四射。主前途光明，贵人相助，时运亨通。',
    fiveElement: '火',
    yinYang: '阳',
  },
  '月': {
    char: '月',
    strokes: 4,
    parts: ['丿', '⺆', '二'],
    meanings: ['月亮', '柔和'],
    overall: '月字如弯月，柔和明亮。主姻缘和美，女性贵人，静待时机。',
    fiveElement: '木',
    yinYang: '阴',
  },
  '金': {
    char: '金',
    strokes: 8,
    parts: ['人', '王', '丷', '一'],
    meanings: ['人为众人', '王为尊贵，金为财富'],
    overall: '金字人王相承，富贵荣华。主财运亨通，金玉满堂，但需正道取财。',
    fiveElement: '金',
    yinYang: '阳',
  },
  '木': {
    char: '木',
    strokes: 4,
    parts: ['十', '八'],
    meanings: ['树木', '生长'],
    overall: '木字扎根向上，生生不息。主事业发展，根深叶茂，循序渐进。',
    fiveElement: '木',
    yinYang: '阳',
  },
  '火': {
    char: '火',
    strokes: 4,
    parts: ['丷', '人'],
    meanings: ['火焰', '热情'],
    overall: '火字旺盛，光明热烈。主事业红火，热情高涨，但需防过犹不及。',
    fiveElement: '火',
    yinYang: '阳',
  },
  '土': {
    char: '土',
    strokes: 3,
    parts: ['十', '一'],
    meanings: ['土地', '根基'],
    overall: '土字稳重，承载万物。主根基稳固，稳步发展，厚积薄发。',
    fiveElement: '土',
    yinYang: '阴',
  },
  '业': {
    char: '业',
    strokes: 5,
    parts: ['丷', '一', '未'],
    meanings: ['事业', '成就'],
    overall: '业字上开下合，事业有成。主业运亨通，稳扎稳打，终成大业。',
    fiveElement: '木',
    yinYang: '阴',
  },
};

// 五行生克关系
export const fiveElementsRelation: Record<string, { generates: string; overcomes: string }> = {
  '金': { generates: '水', overcomes: '木' },
  '木': { generates: '火', overcomes: '土' },
  '水': { generates: '木', overcomes: '火' },
  '火': { generates: '土', overcomes: '金' },
  '土': { generates: '金', overcomes: '水' },
};

// 五行与八卦对应
export const fiveElementToTrigram: Record<string, string[]> = {
  '金': ['乾', '兑'],
  '木': ['震', '巽'],
  '水': ['坎'],
  '火': ['离'],
  '土': ['坤', '艮'],
};
